const products = [
  {
    id: "kylith-75",
    name: "Kylith 75",
    fullName: "Kylith 75 ワイヤレス メカニカルキーボード",
    layout: "75%",
    switches: ["linear", "pulse", "zero", "spark", "cloud"],
    connection: "2.4GHz Wireless / Bluetooth 5.1 / USB-C",
    battery: "5000mAh",
    price: 18800,
    image: "/75.webp",
    series: "basic",
  },
  {
    id: "kylith-75-compact",
    name: "Kylith 75 Compact",
    fullName: "Kylith 75 Compact ワイヤレス メカニカルキーボード",
    layout: "75%",
    switches: ["slim"],
    connection: "2.4GHz Wireless / Bluetooth 5.1 / USB-C",
    battery: "5000mAh",
    price: 18800,
    image: "/75.webp",
    series: "compact",
  },
  {
    id: "kylith-75-HE",
    name: "Kylith 75 HE",
    fullName: "Kylith 75 HE 磁気スイッチ ワイヤレス メカニカルキーボード",
    layout: "75%",
    switches: ["mag"],
    connection: "2.4GHz Wireless / Bluetooth 5.1 / USB-C",
    battery: "5000mAh",
    price: 18800,
    image: "/75-HE.webp",
    status: ["new"],
    series: "he",
  },

  {
    id: "kylith-96",
    name: "Kylith 96",
    fullName: "Kylith 96 ワイヤレス メカニカルキーボード",
    layout: "96%",
    switches: ["linear", "pulse", "zero", "spark", "cloud"],
    connection: "2.4GHz Wireless / Bluetooth 5.1 / USB-C",
    battery: "5000mAh",
    price: 18800,
    image: "/100.webp",
    series: "basic",
  },
  {
    id: "kylith-96-compact",
    name: "Kylith 96 Compact",
    fullName: "Kylith 96 Compact ワイヤレス メカニカルキーボード",
    layout: "96%",
    switches: ["slim"],
    connection: "2.4GHz Wireless / Bluetooth 5.1 / USB-C",
    battery: "5000mAh",
    price: 18800,
    image: "/100.webp",
    series: "compact",
  },
  {
    id: "kylith-96-HE",
    name: "Kylith 96 HE",
    fullName: "Kylith 96 HE 磁気スイッチ ワイヤレス メカニカルキーボード",
    layout: "96%",
    switches: ["mag"],
    connection: "2.4GHz Wireless / Bluetooth 5.1 / USB-C",
    battery: "5000mAh",
    price: 18800,
    image: "/100-HE.webp",
    status: ["new"],
    series: "he",
  },

  {
    id: "kylith-100",
    name: "Kylith 100",
    fullName: "Kylith 100 ワイヤレス メカニカルキーボード",
    layout: "100%",
    switches: ["linear", "pulse", "zero", "spark", "cloud"],
    connection: "2.4GHz Wireless / Bluetooth 5.1 / USB-C",
    battery: "5000mAh",
    price: 18800,
    image: "/100.webp",
    series: "basic",
  },
  {
    id: "kylith-100-compact",
    name: "Kylith 100 Compact",
    fullName: "Kylith 100 Compact ワイヤレス メカニカルキーボード",
    layout: "100%",
    switches: ["slim"],
    connection: "2.4GHz Wireless / Bluetooth 5.1 / USB-C",
    battery: "5000mAh",
    price: 18800,
    image: "/100.webp",
    series: "compact",
  },
  {
    id: "kylith-100-HE",
    name: "Kylith 100 HE",
    fullName: "Kylith 100 HE 磁気スイッチ ワイヤレス メカニカルキーボード",
    layout: "100%",
    switches: ["mag"],
    connection: "2.4GHz Wireless / Bluetooth 5.1 / USB-C",
    battery: "5000mAh",
    price: 18800,
    image: "/100-HE.webp",
    status: ["new"],
    series: "he",
  },
];

export default products;
